name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g serverless
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: go get
        run: go get -u github.com/awslabs/aws-lambda-go-api-proxy
      - name: test
        run: go test ./...
        env:
          ACCESS_TOKEN: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build
        run: env GOOS=linux go build -o bin/main main.go

      - run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}